name: XmoFlake
dependencies:
    - base >= 4.11
    - hostname
    # - simple-cmd
    - aeson
    - directory
    - filepath
executables:
    xmonad:
        main: Main.hs
        source-dirs:
            - xmonad
            - shared
        ghc-options:
            - -O2
        dependencies:
            - containers
            - X11
            - xmonad
            - xmonad-contrib == 0.18.1
            - utf8-string
            - unix
